languageCode = "fr"
languageName = "Français"
weight = 1
title = "blog"

[params]
dateFormat = "2 janvier 2006"
copyright = "© { year } Amine Louzar"

[author]
  name = "Amine Louzar"
  image = "img/avatar.png"
  headline = "Cybersecurity Consultant & Auditor | CTO co-founder"
  bio = "A little bit about me"
  links = [
    { twitter = "https://twitter.com/AmineLz98" },
    { rootme = "https://root-me.org/l3ur" },
  ]
