languageCode = "fr"
languageName = "Français"
weight = 1
title = "blog"

[params]
dateFormat = "2 janvier 2006"
copyright = "© { year } Amine Louzar"

[author]
  name = "Amine Louzar"
  image = "img/avatar.png"
  headline = "Consultant & Auditeur en Cybersécurité | Co-fondateur & CTO"
  bio = "Passionné de cybersécurité et de développement"
  links = [
    { linkedin = "https://www.linkedin.com/in/aminelouzar" },
    { rootme = "https://root-me.org/l3ur" },
  ]
